output:
  format: tab
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - godox
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentFormatting
      - exitAfterDefer
      - hugeParam
      - ifElseChain
      - rangeValCopy
      - unnecessaryBlock
  gofmt:
    simplify: true
  misspell:
    locale: US
    ignore-words:
      - clas
  godox:
    keywords:
      - HACK
      - XXX
