apiVersion: v1
kind: ConfigMap
metadata:
  name: sciuro
data:
  SCIURO_ALERT_RECEIVER: CHANGEME
  SCIURO_ALERTMANAGER_URL: https://CHANGEME.example.com
  SCIURO_CEL_EXPRESSION: '"node" in labels && (labels["node"] == FullName || labels["node"] == ShortName)'
