apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sciuro
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - sciuro-leader
  verbs:
  - update
  - get
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - update
  - delete
  - patch
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
