name: Check
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          repository-cache: true
      - run: bazel --bazelrc=tools/ci.bazelrc build //...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          repository-cache: true
      - run: bazel --bazelrc=tools/ci.bazelrc test //...
