name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch --tags --force
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          repository-cache: true
      - run: bazel --bazelrc=tools/ci.bazelrc run //manifests:stable  > stable.yaml
      - run: bazel --bazelrc=tools/ci.bazelrc run //manifests:cluster > cluster.yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            stable.yaml
            cluster.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
